version: '3'
services:
    node:
        build: .
        ports:
            - ${PORT}:${PORT}
        container_name: docker-node
        depends_on:
            - postgres
        environment:
            - PORT=${PORT}
        restart: always
        volumes:
            - ./logs:/app/logs
            - ./src:/app/src
        networks:
            - my-network
    postgres:
        build: ./src/common
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        container_name: docker-postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - my-network

networks:
    my-network:
        driver: bridge

volumes:
    pgdata: