version: '3'
services:
    node:
        build: .
        ports:
            - ${PORT}:${PORT}
        container_name: docker-node
        depends_on:
            - postgres
        environment:
            - PORT=${PORT}
        restart: always
        volumes:
            - logs:/app/logs
            - ./src:/app/src
        networks:
            - my-network
    postgres:
        build: 
            context: .
            dockerfile: Dockerfile.db
        restart: always
        container_name: docker-postgres
        environment:
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./src:/var/lib/posgresql/data
        networks:
            - my-network

networks:
    my-network:
        driver: bridge
volumes:
    pgdata:
    logs: